# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natpf1", "tcp-port8080,tcp,,8080,,8080"]
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end
  config.nfs.functional = false
end